services:
  backend:
    build: ./backend
    image: devops-backend:local
    container_name: devops-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://localhost:8080"
    image: devops-frontend:local
    container_name: devops-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

